/**
 * MeetKat intake form builder. GENERATED by make_google_form.py: edit config.py, not this file.
 *
 * HOW TO USE (about 2 minutes):
 *  1. Go to https://script.google.com, signed in to the Google account that should own the form.
 *  2. Click "New project". Delete the sample code and paste this whole file.
 *  3. Click Save, then Run (function: createMeetKatForm).
 *  4. Approve the permissions Google asks for (it needs to create a form and a sheet in YOUR Drive).
 *  5. Open "Execution log": it prints the link to share, the edit link and the responses sheet.
 *
 * IMPORTANT: once responses arrive, don't edit question titles or option labels in the form.
 * The code matches answers by their exact text.
 */
function createMeetKatForm() {
  var form = FormApp.create('MeetKat – find a flatmate who fits how you live');
  form.setDescription("A student project matching university students in Hong Kong with compatible flatmates. Takes about 3 minutes.\n\nWhat happens next: in about a week you'll get an email with a private link to 3 suggested flatmates. You rate each one (1 minute). You don't have to be looking for a flatmate right now: just answer as if you were.");
  form.setCollectEmail(false);          // we ask for email as a question instead
  form.setLimitOneResponsePerUser(false); // true would force students to sign in to Google
  form.setProgressBar(true);
  form.setConfirmationMessage("Thanks! In about a week you'll get an email with a private link to 3 suggested flatmates. It takes 1 minute to rate them.");

  form.addPageBreakItem().setTitle("Consent");
  form.addCheckboxItem().setTitle("Consent").setHelpText("Before you start:\n• Your answers are used ONLY to suggest flatmate matches and for anonymous research on how well the matching works.\n• Your written answer is processed by an AI service (Anthropic's Claude API) to understand your preferences. Your name is removed first.\n• Matches see only your FIRST NAME and a short note about what you have in common. Never your email or surname.\n• Your email is shared with a match ONLY if you and they both agree.\n• MeetKat doesn't verify anyone's identity. If you meet someone, meet in a public place first.\n• To delete your data at any time, email your.email@example.com. All data is deleted by 31 January 2027.").setChoiceValues(["I'm 18 or older and I agree to the above"]).setRequired(true);
  form.addPageBreakItem().setTitle("About you");
  form.addTextItem().setTitle("First name").setHelpText("Only your first name is shown to matches.").setRequired(true);
  form.addTextItem().setTitle("Email").setHelpText("Used only to send your private match link. Never shown to anyone.").setRequired(true)
      .setValidation(FormApp.createTextValidation().requireTextIsEmail().setHelpText('Please enter a valid email.').build());
  form.addMultipleChoiceItem().setTitle("If you and a match both say yes, can we share your email with them?").setChoiceValues(["Yes", "No"]).setRequired(true);
  form.addPageBreakItem().setTitle("Your place");
  form.addMultipleChoiceItem().setTitle("Which university do you attend?").setChoiceValues(["HKU – Pok Fu Lam", "CUHK – Sha Tin", "HKUST – Clear Water Bay", "PolyU – Hung Hom", "CityU – Kowloon Tong", "HKBU – Kowloon Tong", "EdUHK – Tai Po"]).showOtherOption(true).setRequired(true);
  form.addMultipleChoiceItem().setTitle("Longest commute to campus you'd accept").setChoiceValues(["Up to 20 minutes", "Up to 30 minutes", "Up to 45 minutes", "Up to 60 minutes", "No preference"]).setRequired(true);
  form.addCheckboxItem().setTitle("Areas you'd live in").setChoiceValues(["Western – Kennedy Town / Sai Ying Pun / Sheung Wan", "Central & Wan Chai – Central / Wan Chai / Causeway Bay", "Southern – Pok Fu Lam / Aberdeen", "Kowloon West – Mong Kok / Yau Ma Tei / Tsim Sha Tsui", "Kowloon Central – Kowloon Tong / Ho Man Tin / Hung Hom", "New Territories East – Sha Tin / Tai Po", "Sai Kung & Tseung Kwan O", "No preference"]).setRequired(true);
  form.addCheckboxItem().setTitle("Monthly rent you'd pay for your room (HKD). Tick every range you'd consider.").setChoiceValues(["Under HK$4000", "HK$4000–4999", "HK$5000–5999", "HK$6000–7499", "HK$7500 or more"]).setRequired(true);
  form.addListItem().setTitle("When do you want to move in?").setChoiceValues(["October 2026", "November 2026", "December 2026", "January 2027", "February 2027", "March 2027", "Flexible"]).setRequired(true);
  form.addPageBreakItem().setTitle("How you live");
  form.addMultipleChoiceItem().setTitle("Sleep schedule").setChoiceValues(["Early – usually asleep before 11pm", "Middle – usually asleep 11pm–1am", "Late – often up past 1am"]).setRequired(true);
  form.addScaleItem().setTitle("How tidy do you keep shared spaces?").setBounds(1, 5).setLabels("Relaxed – a bit of mess is fine", "Spotless – clean up straight away").setRequired(true);
  form.addScaleItem().setTitle("How often do you have guests over?").setBounds(1, 5).setLabels("Almost never", "Most days").setRequired(true);
  form.addScaleItem().setTitle("How much noise at home can you handle?").setBounds(1, 5).setLabels("I need it quiet", "Noise doesn't bother me").setRequired(true);
  form.addMultipleChoiceItem().setTitle("Do you smoke or vape?").setChoiceValues(["No", "Only outdoors", "Yes"]).setRequired(true);
  form.addMultipleChoiceItem().setTitle("Do you have a pet, or plan to bring one?").setChoiceValues(["No", "Yes"]).setRequired(true);
  form.addMultipleChoiceItem().setTitle("How often do you cook at home?").setChoiceValues(["Rarely – mostly eat out or takeaway", "A few times a week", "Most days"]).setRequired(true);
  form.addCheckboxItem().setTitle("Languages you speak comfortably").setChoiceValues(["English", "Cantonese", "Mandarin", "Korean", "Japanese", "Hindi", "Indonesian", "Vietnamese", "French", "German", "Spanish"]).showOtherOption(true).setRequired(true);
  form.addCheckboxItem().setTitle("Dealbreakers – I would NOT live with…").setChoiceValues(["Someone who smokes or vapes (even outdoors)", "Someone with a pet", "Someone who's usually up past 1am", "Someone who has guests over several times a week", "Someone messy", "None of these"]).setRequired(true);
  form.addParagraphTextItem().setTitle("Describe your ideal flatmate and how you live day to day.").setHelpText("For example: your typical weekday, how social you want home to be, what a great flatmate does, and anything that annoys you. A few sentences is perfect (at least 100 characters).").setRequired(true)
      .setValidation(FormApp.createParagraphTextValidation().requireTextLengthGreaterThanOrEqualTo(100).setHelpText('Please write at least 100 characters.').build());

  var sheet = SpreadsheetApp.create('MeetKat responses');
  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());

  Logger.log('SHARE THIS LINK WITH STUDENTS: ' + form.getPublishedUrl());
  Logger.log('Edit the form: ' + form.getEditUrl());
  Logger.log('Responses sheet: ' + sheet.getUrl());
}
